services:

  fastapi_service:
    build: ./backend
    ports:
      - 3003:80 # computer:container
    env_file:
      - env_file.env

  
  streamlit_service:
    build: ./frontend
    env_file:
      - env_file.env

